nginx:
    build: ./nginx/
    ports:
        - "8080:88"
    volumes:
        - ./marabraz:/code
        - ./config/magento.conf:/etc/nginx/conf.d/magento.conf
    links:
        - php
        - mongo
php:
    build: ./php-fpm/
    volumes:
        - ./magento:/code
mongo:
     image: mongo:latest
     ports:
        - "27017:27017"
#    tty: true
#    command: nginx -c /etc/nginx/nginx.conf -g "daemon off;"
