nginx:
    build: ./nginx/
    ports:
        - "80:80"
    volumes:
        - ./buscap/src:/code
        - ./config/nginx.conf:/etc/nginx/nginx.conf
        - ./config/magento.conf:/etc/nginx/conf.d/magento.conf
    links:
        - php
        - mongo
        - redis
        - mysql
php:
    build: ./php-fpm/
    volumes:
        - ./buscap/src:/code
    extra_hosts:
        - "local.buscape.com.br:172.17.0.1"
    links:
        - mysql
        - redis
mongo:
     image: mongo:latest
     ports:
        - "27017:27017"
redis:
    image: redis
    ports:
        - "6379:6379"
mysql:
  image: mysql
  container_name: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes:
    - ./mysql:/var/dumps
