nginx:
    build: ./nginx/
    ports:
        - "80:80"
    volumes:
        - ./magento:/code
        - ./config/magento.conf:/etc/nginx/conf.d/magento.conf
    links:
        - php
        - mongo
        - redis
php:
    build: ./php-fpm/
    volumes:
        - ./magento:/code
    extra_hosts:
        - "dev.marabraz.com.br:172.17.0.1"
mongo:
     image: mongo:latest
     ports:
        - "27017:27017"
redis:
    image: redis
    ports:
        - "6379:6379"
