nginx:
    build: ./nginx/
    ports:
        - "80:88"
    volumes:
        - ./magento:/code
        - ./config/magento.conf:/etc/nginx/conf.d/magento.conf
    links:
        - php
        - mongo
        - mysql
php:
    build: ./php-fpm/
    volumes:
        - ./magento:/code
mongo:
     image: mongo:latest
     ports:
        - "27017:27017"
mysql:
   image: mysql:latest
   hostname: mysql
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USER: usr_marabraz
     MYSQL_PASSWORD: root
     MYSQL_DATABASE: marabraz_04042017
   volumes:
     - ./mysql/dump/mara.sql:/mara.sql
     - ./config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
